# Generated by Django 5.1 on 2025-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="isActive",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="iSuperuser",
            new_name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="isStaff",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
