# Generated by Django 5.1 on 2025-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_isactive_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customerNo", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "customerName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "顧客",
                "db_table": "Customer",
            },
        ),
    ]
