# Generated by Django 5.1 on 2025-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="processNo",
            field=models.IntegerField(max_length=2, unique=True),
        ),
    ]
