# Generated by Django 5.1 on 2025-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_process_processno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.RemoveField(
            model_name="process",
            name="id",
        ),
        migrations.AlterField(
            model_name="category",
            name="categoryName",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="categoryNo",
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="process",
            name="processName",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="process",
            name="processNo",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
