# Generated by Django 5.1 on 2025-07-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_category_id_remove_process_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "projectNo",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                (
                    "projectName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("planTime", models.IntegerField(blank=True, null=True)),
                ("resultTime", models.IntegerField(blank=True, null=True)),
                (
                    "customerNo",
                    models.ForeignKey(
                        db_column="customerNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト",
                "db_table": "Project",
            },
        ),
    ]
