# Generated by Django 5.1 on 2025-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="planTime",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="resultTime",
            field=models.IntegerField(default=0),
        ),
    ]
