# Generated by Django 5.1 on 2025-07-31 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_project_plantime_alter_project_resulttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="userNo",
                    ),
                ),
                ("workDay", models.DateField()),
                ("customerNo", models.IntegerField()),
                (
                    "process",
                    models.ForeignKey(
                        db_column="processNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.process",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_column="projectNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.project",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="categoryNo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.category",
                    ),
                ),
                ("planTime", models.IntegerField()),
                ("resultTime", models.IntegerField()),
            ],
            options={
                "db_table": "WorkRecord",
            },
        ),
    ]
